
require "github/markup"
require "redcarpet"
require "yard"
require "yard/rake/yardoc_task"

YARD::Rake::YardocTask.new do |t|
	OTHER_PATHS = %w()
	t.files = ['lib/**/*.rb', OTHER_PATHS]
	t.options = %w(--markup-provider=redcarpet --markup=markdown --main=README.md)
end

begin
	require 'rspec/core/rake_task'

	RSpec::Core::RakeTask.new(:spec) do |t|
		t.rspec_opts = "-I lib"
	end
rescue LoadError
	# no rspec available
end